---
# https://packages.cisofy.com/community/#debian-ubuntu
- name: Lynis GPG key present
  apt_key:
    id: C80E383C3DE9F082E01391A0366C67DE91CA5D5F
    url: https://packages.cisofy.com/keys/cisofy-software-public.key
    state: present

- name: Lynis APT repo available
  apt_repository:
    repo: "deb https://packages.cisofy.com/community/lynis/deb/ stable main" 
    filename: lynis
    state: present

- name: Pin Lynis APT repo
  copy:
    src: files/lynis
    dest: /etc/apt/preferences.d/lynis

- name: Disable APT translations
  copy:
    src: files/99disable-translations
    dest: /etc/apt/apt.conf.d/99disable-translations

- name: Install Lynis
  apt:
    name: lynis
    state: present
    update_cache: yes

 
