# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_DIFF_ALWAYS: "1"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_FORCE_COLOR: "1"
  MOLECULE_VERBOSITY: "1"
  PIPX_BIN_DIR: /usr/local/bin
  PIPX_HOME: /opt
  PY_COLORS: "1"
stages:
  - bookworm
  - bullseye
  - jammy
  - trixie
trixie:
  image: debian:trixie-backports
  stage: trixie
  script:
    - ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
    - apt-get update -qq
    - apt-get dist-upgrade -qqy
    # Install packages for pipx
    - apt-get install -qqy ansible ansible-lint git jc jo libpq-dev pipx procps postgresql-client python3-apt python3-argcomplete python3-commonmark python3-jmespath python3-lxml python3-netaddr python3-pip python3-psycopg python3-resolvelib python3-ruamel.yaml python3-setuptools python3-venv
    - pipx install molecule
    - pipx inject molecule ansible jc jmespath
    - molecule test
bookworm:
  image: debian:bookworm-backports
  stage: bookworm
  script:
    - ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
    - apt-get update -qq
    - apt-get dist-upgrade -qqy
    # Install packages for pipx
    - apt-get install -qqy ansible ansible-lint git jc jo libpq-dev pipx procps postgresql-client python3-apt python3-argcomplete python3-commonmark python3-jmespath python3-lxml python3-netaddr python3-pip python3-psycopg python3-resolvelib python3-ruamel.yaml python3-setuptools python3-venv
    - pipx install molecule
    - pipx inject molecule ansible jc jmespath
    - molecule test
bullseye:
  image: debian:bullseye-backports
  stage: bullseye
  script:
    - ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
    - apt-get update -qq
    - apt-get dist-upgrade -qqy
    # Install packages for pipx
    - apt-get install -qqy ansible ansible-lint git jc jo libpq-dev pipx procps postgresql-client python3-apt python3-argcomplete python3-commonmark python3-jmespath python3-lxml python3-netaddr python3-pip python3-psycopg2 python3-resolvelib python3-ruamel.yaml python3-setuptools python3-venv
    - pipx install molecule
    - pipx inject --include-apps --include-deps molecule ansible jc jmespath
    - molecule test
jammy:
  image: ubuntu:jammy
  stage: jammy
  script:
    - ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
    - apt-get update -qq
    - apt-get dist-upgrade -qqy
    # Install packages for pipx
    - apt-get install -qqy ansible ansible-lint git jc jo libpq-dev pipx procps postgresql-client python3-apt python3-argcomplete python3-commonmark python3-jmespath python3-lxml python3-netaddr python3-pip python3-psycopg2 python3-resolvelib python3-ruamel.yaml python3-setuptools python3-venv
    - pipx install molecule
    - pipx inject --include-apps --include-deps molecule ansible jc jmespath
    - molecule test
# vim: syntax=yaml
...
