# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_DIFF_ALWAYS: "1"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "1"
  ANSIBLE_FORCE_COLOR: "1"
  GIT_STRATEGY: none
  MOLECULE_VERBOSITY: "3"
  PY_COLORS: "1"
before_script:
  - apt-get update -qq
  - apt-get dist-upgrade -qqy
  - apt-get install -qqy ansible git pipx python3-apt sudo
  - useradd -m -U ansible
  - echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  - chmod 700 /home/ansible
  - su - ansible
  - cd
  - pipx install molecule
  - ls -lah /root/.local/bin
  - pipx ensurepath
  - source ~/.profile
  - mkdir -p builds/${CI_PROJECT_ROOT_NAMESPACE}
  - cd builds/${CI_PROJECT_ROOT_NAMESPACE}
  - git clone ${CI_PROJECT_URL}.git
  - cd ${CI_PROJECT_NAME}
stages:
  - bookworm
  - bullseye
  - jammy
bookworm:
  image: debian:bookworm-backports
  stage: bookworm
  script:
    - molecule test
bullseye:
  image: debian:bullseye-backports
  stage: bullseye
  script:
    - molecule test
jammy:
  image: ubuntu:jammy
  stage: jammy
  script:
    - molecule test
# vim: syntax=yaml
...
