---
- name: ssh
  src: https://git.coop/webarch/ssh.git
  version: master
  scm: git

- name: apt
  src: https://git.coop/webarch/apt.git
  version: master
  scm: git

- name: munin-node
  src: https://git.coop/webarch/munin-node.git
  version: master
  scm: git

