---
- name: Webarchitects Debian Server Config
  hosts: "{{ hostname }}"
  become: yes

  roles:
    - bash
    - apt
    - ssh
    - vim
    - locale
    - munin-node
    - chrony
    - rsync
    - screen
    - mutt

