---
- name: Packages installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - apticron
    - aptitude
    - apt-listchanges
    - apt-show-versions
    - git

# Gandi servers don't have /etc/apt/sources.list and have HTTPS enabled already
- name: Stat /etc/apt/sources.list
  stat:
    path: "/etc/apt/sources.list"
  register: sources_list

- block:

  - name: Use HTTPS mirror for {{ distro }} apt packages 
    lineinfile:
      backup: yes
      backrefs: yes
      state: present
      dest: "/etc/apt/sources.list"
      regexp: '^deb\s+http://httpredir.debian.org/debian'
      line: "deb     https://www.mirrorservice.org/sites/ftp.debian.org/debian/     {{ distro }} main contrib non-free"
    when: ( distro == 'jessie' ) or ( distro == 'stretch' )
  
  - name: Use HTTPS mirror for {{ distro }} apt source packages 
    lineinfile:
      backup: yes
      backrefs: yes
      state: present
      dest: "/etc/apt/sources.list"
      regexp: '^deb-src\s+http://httpredir.debian.org/debian'
      line: "deb-src https://www.mirrorservice.org/sites/ftp.debian.org/debian/     {{ distro }} main contrib non-free"
    when: ( distro == 'jessie' ) or ( distro == 'stretch' )

  when: sources_list.stat.exists == True

- name: Checkout Webarchitects scripts
  git:
    repo: https://git.coop/webarch/scripts.git 
    dest: /usr/local/src/scripts
    update: yes

- name: Install Webarchitects scripts
  command: /usr/local/src/scripts/install.sh 
