---
- name: Packages installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - apticron
    - aptitude
    - apt-listchanges
    - apt-show-versions
    - git

# Gandi servers don't have /etc/apt/sources.list and have HTTPS enabled already
- name: Stat /etc/apt/sources.list
  stat:
    path: "/etc/apt/sources.list"
  register: sources_list

- name: /etc/apt/sources.list in place
  template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    backup: yes
  when: sources_list.stat.exists == True

- name: Checkout Webarchitects scripts
  git:
    repo: https://git.coop/webarch/scripts.git 
    dest: /usr/local/src/scripts
    update: yes

- name: Install Webarchitects scripts
  command: /usr/local/src/scripts/install.sh 
