---
# apt-transport-https needs to be installed before the sources.list is updated to use HTTPS
- name: Packages installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - apticron
    - aptitude
    - apt-listchanges
    - apt-show-versions
    - git

# Gandi servers don't have /etc/apt/sources.list and have HTTPS enabled already
- name: Stat /etc/apt/sources.list
  stat:
    path: "/etc/apt/sources.list"
  register: sources_list

- name: /etc/apt/sources.list in place
  template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    backup: yes
  when: sources_list.stat.exists == True

- name: Checkout Webarchitects scripts
  git:
    repo: https://git.coop/webarch/scripts.git 
    dest: /usr/local/src/scripts
    update: yes

- name: Install Webarchitects scripts
  command: /usr/local/src/scripts/install.sh 

- name: Check for updates
  command: apt-show-versions -b -u
  register: packages

- block:

  - name: Dist upgrade
    apt:
      update_cache: no
      upgrade: dist
    register: dist_upgrade

  - name: Update the Changelog
    command: "logchange {{ packages.stdout }}"

  when: packages.stdout != ""
