---
- name: Install Ansible and modules
  block:

    - name: Ansible present using pip
      ansible.builtin.pip:
        name: "ansible-core=={{ ans_version }}"
        state: present
        executable: /usr/bin/pip3

    - name: Ansible dependances present
      ansible.builtin.pip:
        name: "{{ pkg }}"
        state: present
        executable: /usr/bin/pip3
      loop:
        - jc
        - jmespath
        - netaddr
      loop_control:
        loop_var: pkg

    - name: Bash completion present using argcomplete
      ansible.builtin.command: activate-global-python-argcomplete3

  tags:
    - ans
...
