---
- name: Install Ansible dependencies and auto-completion
  block:

    - name: Ansible dependencies present
      ansible.builtin.pip:
        name: "{{ ans_pip_pkg }}"
        state: present
        executable: "{{ ans_pip3 }}"
        extra_args: --user
      loop: "{{ ans_pip_req }}"
      loop_control:
        loop_var: ans_pip_pkg

    - name: Ansible present using pip
      ansible.builtin.pip:
        name: "ansible-core=={{ ans_version }}"
        state: present
        executable: "{{ ans_pip3 }}"
        extra_args: --user
      register: ans_pip_install

    - name: Debug the install results
      absible.builtin.debug:
        var: ans_pip_install.stdout
        verbosity: 2

    - name: Bash completion present using argcomplete present system-wide
      ansible.builtin.command: activate-global-python-argcomplete3
      args:
        creates: /etc/bash_completion.d/python-argcomplete.sh
      when: ansible_effective_user_id == 0

    - name: Bash completion present using argcomplete present locally
      ansible.builtin.command: activate-global-python-argcomplete3 --user
      args:
        creates: ~/.bash_completion.d/python-argcomplete.sh
      when: ansible_effective_user_id != 0

  tags:
    - ans
...
