---
- name: Check variables
  block:

    - name: Check which the default version of Ansible is
      command: which ansible
      check_mode: false
      changed_when: false
      register: ans_which_ansible
      failed_when: ans_which_ansible.rc is not regex('^0|1$')

    - name: Ansible needs to be installed
      assert:
        that:
          - ans_which_ansible.rc == 0
        fail_msg: "Please install Ansible!"

    - name: Set a variable for the path for the default version of Ansible
      set_fact:
        ans_default: "{{ ans_which_ansible.stdout | string }}"

    - name: Check the default version of Ansible
      command: "{{ ans_default }} --version"
      check_mode: false
      changed_when: false
      register: ans_default_version_installed

    - name: Set a fact for the default version of Ansible
      set_fact:
        ans_default_version: "{{ ans_default_version_installed.stdout_lines[0] | regex_replace('ansible') | regex_replace('[core') | regex_replace(']') | trim | string }}"

    - name: Ansible default version
      debug:
        var: ans_default_version

    - name: "Check that the default version of Ansible {{ ans_default_version }} is greater than or equal to 2.9.0"
      assert:
        that:
          - ( ans_default_version | string ) is version('2.9.0', '>=')

    - name: Check if a distro version of Ansible is installed
      stat:
        path: /usr/bin/ansible
      register: ans_distro_version_path

    - name: Check the distro version of Ansible
      block:

        - name: Check the distro version of Ansible
          command: /usr/bin/ansible --version
          check_mode: false
          changed_when: false
          register: ans_distro_version_installed

        - name: Set a fact for the distro version of Ansible
          set_fact:
            ans_distro_version: "{{ ans_distro_version_installed.stdout_lines[0] | regex_replace('^ansible ') | trim | string }}"

        - name: Ansible distro version
          debug:
            var: ans_distro_version

        - name: Assert that this role is not being asked to install a local version of Ansible that matches the distro version
          assert:
            that: ( ans_version | string ) is not version(ans_distro_version, '==')

      when: ( ans_distro_version_path.stat.exists is defined ) and ( ans_distro_version_path.stat.exists )

    - name: Check if a local version of Ansible is installed
      stat:
        path: /usr/local/bin/ansible
      register: ans_local_version_path

    - name: Check the local version of Ansible when present
      block:

        - name: Check the local version of Ansible
          command: /usr/local/bin/ansible --version
          check_mode: false
          changed_when: false
          register: ans_local_version_installed

        - name: Set a fact for the local version of Ansible
          set_fact:
            ans_local_version: "{{ ans_local_version_installed.stdout_lines[0] | regex_replace('^ansible ') | trim | string }}"

        - name: "Ansible /usr/bin/ansible version"
          debug:
            var: ans_local_version

      when: ( ans_local_version_path.stat.exists is defined ) and ( ans_local_version_path.stat.exists )

    - name: Get a list of available pypi Ansible core versions
      uri:
        url: https://pypi.org/pypi/ansible-core/json
        method: GET
        return_content: true
      check_mode: false
      changed_when: false
      register: ans_pypi

    - name: Create an array of the Ansible core versions available
      set_fact:
        ans_versions_available: "{{ ans_versions_available | default([]) }} + [ '{{ ver.key | string }}' ]"
      loop: "{{ ans_pypi.json.releases | dict2items }}"
      loop_control:
        loop_var: ver
        label: "{{ ver.key }}"

    - name: "Check that that the proposed Ansible core version {{ ans_version }} is available via pypi"
      assert:
        that:
          - ans_version in ans_versions_available

    - name: Check if Ansible has been installed using pip
      command: /usr/bin/pip3 --no-color -q show ansible-core
      check_mode: false
      changed_when: false
      register: ans_show_ansible
      failed_when: ans_show_ansible.rc is not regex('^0|1$')

    - name: Set a variable to indicate that Ansible has been installed using pip
      set_fact:
        ans_ansible_pip: "{% if ans_show_ansible.rc == 0 %}present{% else %}absent{% endif %}"

    - name: Debug Ansible versions
      debug:
        msg:
          - "The distro Ansible /usr/bin/ansible {% if ans_distro_version is defined %}is version {{ ans_distro_version }}{% else %} not installed{% endif %}"
          - "The local Ansible /usr/local/bin/ansible {% if ans_local_version is defined %}is version {{ ans_local_version }}{% else %}not installed{% endif %}"
          - "The default Ansible {{ ans_which_ansible.stdout }} is version {{ ans_default_version }}"

  tags:
    - ansible
...
