---
- name: Check variables
  block:

    - name: Stat ansible
      ansible.builtin.stat:
        path: "{{ ans_default }}"
      register: ans_stat_ansible

    - name: Ansible needs to be installed
      ansible.builtin.assert:
        that:
          - ans_stat_ansible.stat.exists | bool
        fail_msg: "Please install Ansible!"
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Get the apt package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Debug the installed Ansible package version string
      ansible.builtin.debug:
        var: ansible_facts.packages.ansible[0].version
        verbosity: 1

    - name: Set a fact for the .deb package Ansible version
      ansible.builtin.set_fact:
        ans_installed_version: "{{ ansible_facts.packages.ansible[0].version | regex_replace('[+].*$') | string }}"

    - name: Ansible installed version
      ansible.builtin.debug:
        var: ans_installed_version
        verbosity: 1

    - name: Set facts for the mininum and installed versions of Ansible as strings
      ansible.builtin.set_fact:
        ans_installed_version_string: "{{ ans_installed_version | string }}"
        ans_default_min_version_string: "{{ ans_default_min_version | string }}"

    - name: Debug the variable type for ans_installed_version_string
      ansible.builtin.debug:
        msg: "{{ ans_installed_version | type_debug }}"
        verbosity: 3

    - name: Debug the variable type for ans_default_min_version_string
      ansible.builtin.debug:
        msg: "{{ ans_default_min_version | type_debug }}"
        verbosity: 3

    - name: Check that the installed version of Ansible is greater than or equal to the minimum version required
      ansible.builtin.assert:
        that:
          - ans_installed_version_string is version(ans_default_min_version_string, '>=')
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Get a list of available pypi Ansible core versions
      ansible.builtin.uri:
        url: https://pypi.org/pypi/ansible-core/json
        method: GET
        return_content: true
        validate_certs: "{% if ansible_version.full == ans_default_min_version %}false{% else %}true{% endif %}"
      check_mode: false
      changed_when: false
      register: ans_pypi

    - name: Debug available Ansible versions
      ansible.builtin.debug:
        var: ans_pypi.json.releases
        verbosity: 3

    - name: Create an array of the stable Ansible core versions available and set a variables for the latest version
      ansible.builtin.set_fact:
        ans_versions_available: "{{ ans_pypi.json.releases.keys() | reject('regex', '[a-z]') }}"
        ans_version_latest: "{{ ans_pypi.json.info.version }}"

    - name: Check that that the proposed Ansible core version is available via pypi
      ansible.builtin.assert:
        that:
          - ans_version in ans_versions_available
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Check if Ansible has been installed using pip
      ansible.builtin.command: "{{ ans_pip3 }} --no-color -q show ansible-core"
      check_mode: false
      changed_when: false
      register: ans_show_ansible
      failed_when: ans_show_ansible.rc is not regex('^0|1$')

    - name: Set a variable to indicate that Ansible has been installed using pip
      ansible.builtin.set_fact:
        ans_ansible_pip: "{% if ans_show_ansible.rc == 0 %}present{% else %}absent{% endif %}"

    - name: Debug Ansible version
      ansible.builtin.debug:
        msg: "The version of Ansible at {{ ans_default }} is version {{ ans_installed_version }}"
        verbosity: 1

    - name: Check the Ansible Galaxy version
      ansible.builtin.command: "{{ ans_galaxy_default }} --version"
      check_mode: false
      changed_when: false
      register: ans_galaxy_check_version

    - name: Set a fact for the version of Ansible Galaxy installed
      ansible.builtin.set_fact:
        ans_galaxy_installed_version: "{{ ans_galaxy_check_version.stdout_lines[0] | regex_replace('^ansible-galaxy \\[core ') | regex_replace('\\]$') }}"

    - name: Get the Ansible Galaxy configured module search paths
      ansible.builtin.set_fact:
        ans_galaxy_module_search_paths: "{{ (line | regex_replace('^  configured module search path = \\[') | regex_replace('\\]$') | regex_replace(\"'\")). split(', ') | list }}"
      when: line is regex('^  configured module search path')
      loop: "{{ ans_galaxy_check_version.stdout_lines }}"
      loop_control:
        loop_var: line

    - name: Debug Ansible Galaxy configured module search paths
      ansible.builtin.debug:
        var: ans_galaxy_module_search_paths
        verbosity: 2

  tags:
    - ansible
...
