---
- name: Install Ansible collection
  block:

    - name: Set a fact for the proposed version when not the latest
      ansible.builtin.set_fact:
        ans_collection_proposed: "{{ col.version | string }}"
      when: col.version != "latest"

    - name: Get the latest version number
      block:

        - name: Use a HEAD request to get the latest redirect URL
          ansible.builtin.uri:
            url: "https://github.com/ansible-collections/{{ col.name }}/releases/latest"
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          changed_when: false
          register: ans_latest_headers

        - name: Set a fact for the latest version
          ansible.builtin.set_fact:
            ans_collection_proposed: "{{ ans_latest_headers.location | urlsplit('path') | basename | string }}"

      when: col.version == "latest"

    # TODO check the installed version using ansible-galaxy collection list {{ col.name }}

    - name: Install collection
      command: "ansible-galaxy collection install {{ col.name }}:=={{ ans_collection_proposed }}"
      become: false

  tags:
    - ans
...
