---
# If using community.general.ansible_galaxy_install fails
# then fall back to using the command line see:
# https://github.com/ansible-collections/community.general/issues/5661

- name: Install collection
  block:

    - name: Install collection using ansible_galaxy_install module
      community.general.ansible_galaxy_install:
        name: "{{ col.name }}:{{ ans_collection_proposed }}"
        force: true
        type: collection
      become: false

  rescue:

    - name: Install collection using command module
      ansible.buiultin.command: >-
        {{ ans_galaxy_default }} collection install 
        {{ col.name }}:{{ ans_collection_proposed }} --force 
      register: ans_collection_install

  tags:
    - ans
...
