---
- name: Debug variables
  block:

    - name: Debug available versions
      debug:
        var: ans_versions_available

    - name: Loop through the Ansible versions available to check the veriable type
      debug:
        msg: "Ansible version {{ version }} is {{ version | type_debug }}"
      loop: "{{ ans_versions_available }}"
      loop_control:
        loop_var: version
        label: "{{ version }}"

    - name: Debug Ansible version type
      debug:
        msg:
          - "Ansible version {{ ans_version }} is {{ ans_version | type_debug }}"

  tags:
    - ansible
...
