---
- name: Install Ansible lint
  block:

    - name: Latest Ansible Lint present
      block:

        - name: Check the latest version of Ansible Lint
          ansible.builtin.uri:
            url: https://github.com/ansible/ansible-lint/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          changed_when: false
          register: ans_lint_headers

        - name: Debug Ansible Lint latest headers
          ansible.builtin.debug:
            msg:
              - "Location: {{ ans_lint_headers.location }}"
              - "Path: {{ ans_lint_headers.location | urlsplit('path') }}"
              - "Version: {{ ans_lint_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"
            verbosity: 2

        - name: Set a fact for the latest version of Ansible Lint
          ansible.builtin.set_fact:
            ans_lint_version_latest: "{{ ans_lint_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"

        - name: Latest Ansible Lint present
          ansible.builtin.pip:
            name: "ansible-lint=={{ ans_lint_version_latest }}"
            state: present
            executable: /usr/bin/pip3

      when: ans_installed_version is ansible.builtin.version('2.10.17', '>')

    - name: Legacy Ansible Lint present
      ansible.builtin.pip:
        name: "ansible-lint==5.4.0"
        state: present
        executable: /usr/bin/pip3
      when: ans_installed_version is ansible.builtin.version('2.10.17', '<=')

  tags:
    - ans
...
