# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Check, install, reinstall and remove PyPI package using pip
  block:

    - name: "Set a fact for the proposed state for {{ ans_pypi_pkg.name }}"
      ansible.builtin.set_fact:
        ans_pypi_pkg_state: "{{ ans_pypi_pkg.state | default('present') }}"

    - name: "Debug PyPI package proposed state for {{ ans_pypi_pkg.name }}"
      ansible.builtin.debug:
        var: ans_pypi_pkg_state
        verbosity: "{% if ansible_check_mode | bool %}1{% else %}2{% endif %}"

    - name: Include PyPi info tasks when the PyPI package is not set to be absent
      ansible.builtin.include_tasks: pypi_info.yml
      when: ans_pypi_pkg_state != "absent"

    - name: "Set a fact for the system PyPi package version number if present for {{ ans_pypi_pkg.name }}"
      ansible.builtin.set_fact:
        ans_pypi_system_version_present: "{{ ans_pip_system_existing | community.general.json_query(ans_pypi_pkg_version_jmespath_query) }}"

    - name: "Set a fact for the user PyPi package version number if present for {{ ans_pypi_pkg.name }}"
      ansible.builtin.set_fact:
        ans_pypi_user_version_present: "{{ ans_pip_user_existing | community.general.json_query(ans_pypi_pkg_version_jmespath_query) }}"

    - name: Set a fact for the extras when present
      ansible.builtin.set_fact:
        ans_pypi_extras: "{{ ans_pip_metadata | community.general.json_query(ans_pypi_extras_jmespath_query) }}"
      when: >-
        ( ans_pip_metadata is defined ) and
        ( ( ( ans_pypi_system_version_present is defined ) and ( ans_pypi_system_version_present | length > 0 ) ) or
        ( ( ans_pypi_user_version_present is defined ) and ( ans_pypi_user_version_present | length > 0 ) ) )

    - name: "Debug PyPi version variables for {{ ans_pypi_pkg.name }}"
      ansible.builtin.debug:
        msg:
          - "ans_pypi_pkg_state: {{ ans_pypi_pkg_state }}"
          - "ans_pypi_version_latest: {{ ans_pypi_version_latest }}"
          - "ans_pypi_version_required: {{ ans_pypi_version_required }}"
          - "ans_pypi_system_version_present: {{ ans_pypi_system_version_present }}"
          - "ans_pypi_user_version_present: {{ ans_pypi_user_version_present }}"
          - "ans_pypi_extras: {% if ans_pypi_extras is defined %}{{ ans_pypi_extras }}{% endif %}"
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: PyPI package present using pip
      block:

        - name: Only downgrade packages when ans_downgrade is true
          block:

            - name: "PyPi system package present {{ ans_pypi_pkg.name }}{% if ans_pypi_pkg.extras is defined %}[{% for extra in ans_pypi_pkg.extras %}{{ extra }}{% if not loop.last %},{% endif %}{% endfor %}]{% endif %}=={{ ans_pypi_version_required }}"  # noqa args[module] name[template]
              ansible.builtin.pip:
                name: "{{ ans_pypi_pkg.name }}{% if ans_pypi_pkg.extras is defined %}[{% for extra in ans_pypi_pkg.extras %}{{ extra }}{% if not loop.last %},{% endif %}{% endfor %}]{% endif %}=={{ ans_pypi_version_required }}"
                state: "{{ ans_pypi_pkg_state }}"
                executable: "{{ ans_pip_path }}"
                extra_args: "{% if ansible_facts.python_version is version('3.11.2', '>=') %}--break-system-packages{% endif %}"
              when:
                - ansible_effective_user_id == 0
                - ans_pypi_pkg_state is regex('^forcereinstall|present$')

            - name: "PyPi user package present {{ ans_pypi_pkg.name }}{% if ans_pypi_pkg.extras is defined %}[{% for extra in ans_pypi_pkg.extras %}{{ extra }}{% if not loop.last %},{% endif %}{% endfor %}]{% endif %}=={{ ans_pypi_version_required }}"  # noqa args[module] name[template]
              ansible.builtin.pip:
                name: "{{ ans_pypi_pkg.name }}{% if ans_pypi_pkg.extras is defined %}[{% for extra in ans_pypi_pkg.extras %}{{ extra }}{% if not loop.last %},{% endif %}{% endfor %}]{% endif %}=={{ ans_pypi_version_required }}"
                state: "{{ ans_pypi_pkg_state }}"
                executable: "{{ ans_pip_path }}"
                extra_args: "--user{% if ansible_facts.python_version is version('3.11.2', '>=') %} --break-system-packages{% endif %}"
              when:
                - ansible_effective_user_id != 0
                - ans_pypi_pkg_state is regex('^forcereinstall|present$')

          when: >-
            ( ( not ans_downgrade | bool ) and
            ( ( ( ans_pypi_system_version_present is defined ) and
            ( ans_pypi_system_version_present | length > 0 ) and
            ( ans_pypi_version_required is version(ans_pypi_system_version_present, 'gt') ) ) or
            ( ( ans_pypi_user_version_present is defined ) and
            ( ans_pypi_user_version_present | length > 0 ) and
            ( ans_pypi_version_required is version(ans_pypi_user_version_present, 'gt') ) ) or
            ( ( ans_pypi_system_version_present is defined ) and
            ( ans_pypi_system_version_present | length == 0 ) and
            ( ans_pypi_user_version_present is defined ) and
            ( ans_pypi_user_version_present | length == 0 ) ) ) ) or
            ( ( ans_downgrade | bool ) and
            ( ( ( ans_pypi_system_version_present is defined ) and
            ( ans_pypi_system_version_present | length > 0 ) and
            ( ans_pypi_version_required is version(ans_pypi_system_version_present, 'lt') ) ) or
            ( ( ans_pypi_user_version_present is defined ) and
            ( ans_pypi_user_version_present | length > 0 ) and
            ( ans_pypi_version_required is version(ans_pypi_user_version_present, 'lt') ) ) or
            ( ( ans_pypi_system_version_present is defined ) and
            ( ans_pypi_system_version_present | length == 0 ) and
            ( ans_pypi_user_version_present is defined ) and
            ( ans_pypi_user_version_present | length == 0 ) ) ) )

      when:
        - ans_pypi_pkg.url is defined
        - ans_pypi_pkg.version is defined
        - ans_pypi_pkg_state != "absent"

    - name: PyPI package absent using pip
      block:

        - name: "PyPi root user package absent {{ ans_pypi_pkg.name }}"
          ansible.builtin.pip:
            name: "{{ ans_pypi_pkg.name }}"
            state: absent
            executable: "{{ ans_pip_path }}"
            extra_args: "{% if ansible_facts.python_version is version('3.11.2', '>=') %}--break-system-packages{% endif %}"
          when:
            - ansible_effective_user_id == 0
            - ans_pypi_system_version_present is defined
            - ans_pypi_system_version_present | length > 0

        - name: "PyPi user package absent {{ ans_pypi_pkg.name }}"
          ansible.builtin.pip:
            name: "{{ ans_pypi_pkg.name }}"
            state: absent
            executable: "{{ ans_pip_path }}"
            extra_args: "{% if ansible_facts.python_version is version('3.11.2', '>=') %}--break-system-packages{% endif %}"
          when:
            - ansible_effective_user_id != 0
            - ans_pypi_user_version_present is defined
            - ans_pypi_user_version_present | length > 0

      when: >-
        ( ans_pypi_pkg_state == "absent" ) or
        ( ( not ans_downgrade | bool ) and
        ( ans_pypi_version_required is defined ) and
        ( ans_pypi_system_version_present is defined ) and
        ( ans_pypi_system_version_present | length > 0 ) and
        ( ans_pypi_system_version_present is version(ans_pypi_version_required, '>=') ) )

  tags:
    - ans
...
