# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
argument_specs:
  main:
    author: Chris Croome
    description: An Ansible role for installing Ansible.
    short_description: The main entry point for the Ansible role.
    options:
      ans:
        type: bool
        required: true
        description: Run the tasks in this role.
      ans_cols:
        type: list
        required: false
        description: Ansible collections to install.
        elements: dict
        options:
          name:
            type: str
            required: true
            description: The name of the Ansible collection to install.
          url:
            type: str
            required: true
            description: The URL of the Ansible collection to install.
          version:
            type: str
            required: true
            description: The version of the Ansible collection to install.
      ans_distro_check:
        type: bool
        required: true
        description: Enable or disable the ansible_distribution and ansible_distribution_release check.
      ans_downgrade:
        type: bool
        required: true
        description: Enable or disable the installing of older versions of packages than the system packages.
      ans_env:
        type: dict
        required: true
        description: An internal dictionary of environment variables to use when running ansible.
      ans_pkgs_debian:
        type: list
        required: true
        description: A list of Debian packages that are required.
        elements: str
      ans_pkgs_debian_bullseye:
        type: list
        required: true
        description: A list of Debian packages that are required for Buster and Bullseye.
        elements: str
      ans_pkgs_ubuntu:
        type: list
        required: true
        description: A list of Ubuntu packages that are required.
        elements: str
      ans_pypi_pkgs:
        type: list
        required: true
        description: A list of PyPI, Python Package Index packages to install.
        elements: dict
        options:
          name:
            type: str
            required: true
            description: The name of the PyPI package.
          extras:
            type: list
            required: false
            description: A list of extras, optional variants of a package, which may include additional dependencies.
            elements: str
          state:
            type: str
            required: false
            description: The state to pass to the ansible.builtin.pip module.
            choices:
              - "absent"
              - "forcereinstall"
              # Use version for latest
              # - "latest"
              - "present"
          type:
            type: str
            required: false
            description: The type of the PyPI package.
            choices:
              - app
              - lib
          url:
            type: str
            required: false
            description: The URL of the PyPI package.
          venv:
            type: str
            required: false
            description: The pipx venv to inject the package into, if it exists and pip is not being used.
          version:
            type: str
            required: false
            description: The version of PyPI package.
      ans_pipx_executable_version:
        type: str
        required: false
        description: The version of pipx returned when testing the pipx executable variable.
      ans_pipx_path:
        type: str
        required: true
        description: The path to pipx for community.general.pipx_info.
      ans_pipx_root_env:
        type: dict
        required: false
        description: The pipx environment variables for the root user.
        options:
          PIPX_HOME:
            type: str
            required: false
            description: The PIPX_HOME environment variable value for pipx when run as root.
          PIPX_BIN_DIR:
            type: str
            required: false
            description: The PIPX_BIN_DIR environment variable value for pipx when run as root.
      ans_pipx_user_env:
        type: dict
        required: false
        description: The pipx environment variables for a regular user.
        options:
          PIPX_HOME:
            type: str
            required: false
            description: The PIPX_HOME environment variable value for pipx when run as a regular user.
          PIPX_BIN_DIR:
            type: str
            required: false
            description: The PIPX_BIN_DIR environment variable value for pipx when run as a regular user.
      ans_python_path:
        type: str
        required: true
        description: The path to the system python3 binary.
      ans_python_version:
        type: str
        required: false
        description: The version of Python installed.
      ans_user_bin:
        type: str
        required: false
        description: The non-root user bin dir.
...
