# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
argument_specs:
  main:
    author: Chris Croome
    description: An Ansible role for installing Ansible.
    short_description: The main entry point for the Ansible role.
    options:
      ans:
        type: bool
        required: true
        description: Run the tasks in this role.
      ans_cols:
        type: list
        required: true
        description: Ansible collections to install.
        elements: dict
        options:
          name:
            type: str
            required: true
            description: The name of the Ansible collection to install.
          url:
            type: str
            required: true
            description: The URL of the Ansible collection to install.
          version:
            type: str
            required: true
            description: The version of the Ansible collection to install.
      ans_pkgs:
        type: list
        required: true
        description: A list of Debian / Ubuntu packages that are required.
        elements: str
      ans_pypi_pkgs:
        type: list
        required: true
        description: A list of PyPI, Python Package Index packages to install.
        elements: dict
        options:
          name:
            type: str
            required: true
            description: The name of the PyPI package.
          extras:
            type: list
            required: false
            description: A list of extras, optional variants of a package, which may include additional dependencies.
            elements: str
          state:
            type: str
            required: false
            description: The state to pass to the ansible.builtin.pip module.
            choices:
              - "absent"
              - "forcereinstall"
              # Use version for latest
              # - "latest"
              - "present"
          url:
            type: str
            required: false
            description: The URL of the PyPI package.
          version:
            type: str
            required: false
            description: The version of PyPI package.
...
