# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
# https://docs.ansible.com/ansible/latest/playbook_guide/complex_data_manipulation.html
ansvarnames: "{{ q('varnames', '^ans_') | sort }}"
anshostvars: "{{ dict(ansvarnames | list | ansible.builtin.zip(q('vars', *ansvarnames))) }}"
# Jammy hass 2.10.8
# https://packages.ubuntu.com/jammy/ansible
ans_ansible_core_min_version: "2.10.8"
ans_ansible_path: "{{ ans_bin }}/ansible"
ans_bash: "{% if ansible_facts.env.SHELL is defined and ansible_facts.env.SHELL is regex('bash$') %}{{ ansible_facts.env.SHELL }}{% else %}/bin/bash{% endif %}"
ans_bin: /usr/bin
# https://packages.ubuntu.com/jammy/ansible
ans_jammy_versions:
  - 2.10.7+merged+base+2.10.8+dfsg-1
  - 2.10.7+merged+base+2.10.17+dfsg-0+deb11u1
  - 2.10.7+merged+base+2.10.17+dfsg-0+deb11u2
  - 2.10.7+merged+base+2.10.17+dfsg-0+deb11u3
ans_col_comgen_jmespath_query: "[?name=='community.general']"
ans_col_comgen_ver_jmespath_query: "[?name=='community.general'].version|[0]"
ans_col_comgen_vers_jmespath_query: "[?name=='community.general'].version"
ans_col_existing: []
ans_col_list_jmespath_query: "[*].{name: name,version: value.version}"
ans_comgen: false
ans_col_path_system: /usr/lib/python3/dist-packages/ansible_collections
ans_col_path_user: "{{ ansible_facts.env.HOME }}/.ansible/collections/ansible_collections"
ans_deb_name_jmespath_query: '"ansible-core"[0].name'
ans_deb_version_jmespath_query: '"ansible-core"[0].version'
ans_distros: "{{ (ans_pkgs | community.general.json_query('[].name')) }}"
ans_env:
  ANSIBLE_FORCE_COLOR: "0"
  ANSIBLE_NOCOLOR: "1"
  ANSIBLE_NOCOWS: "1"
  PY_COLORS: "0"
# Don't use community.general.ansible_galaxy_install by default because of this issue
# https://github.com/ansible-collections/community.general/issues/5661
ans_galaxy_install_mod: false
# JMESPath queries
# TODO Move other JMESPath query variables below into this dictionary
ans_jpq:
  pkgs_absent: "[?name=='{{ ansible_facts.distribution_release }}'].pkgs_absent|[0]"
  pkgs_present: "[?name=='{{ ansible_facts.distribution_release }}'].pkgs_present|[0]"
ans_pip_path: "{{ ans_bin }}/pip3"
ans_pypi_ansible_core_state_jmespath_query: "[?name=='ansible-core'].state|[0]"
ans_pypi_ansible_core_version_jmespath_query: "[?name=='ansible-core'].version|[0]"
ans_pypi_ansible_state_jmespath_query: "[?name=='ansible'].state|[0]"
ans_pypi_ansible_version_jmespath_query: "[?name=='ansible'].version|[0]"
ans_pypi_pkg_uninstall: []
ans_pipx_apps_jmespath_query: "application[].name"
ans_pipx_bin_jmespath_query: "files[?mode=='0775'].path"
ans_pipx_info_ansible_version_jmespath_query: "application[?name=='ansible'].version|[0]"
ans_pipx_info_injected_pkgs_jmespath_query: "application[?name=='ansible'].injected|[0]"
ans_pipx_info_pkgs_jmespath_query: "application[].{name: name,version: version}"
ans_pipx_inject: []
ans_pipx_list_ansible_version_jmespath_query: "venvs.ansible.metadata.main_package.package_version"
ans_pipx_list_injected_pkgs_jmespath_query: "venvs.ansible.metadata.injected_packages.*.{name: package,version: package_version}"
ans_pipx_list_pkgs_jmespath_query: "venvs.*.metadata[].main_package.{name: package,version: package_version}"
ans_pipx_mod: false
ans_pipx_mod_info: false
ans_pkgs_absent: "{{ ans_pkgs | community.general.json_query(ans_jpq.pkgs_absent) }}"
ans_pkgs_present: "{{ ans_pkgs | community.general.json_query(ans_jpq.pkgs_present) }}"
# The following array can be generated by running
# bash versions.sh > versions.yml

ans_versions:
  - ansible: 2.10.0
    base: 2.10.1
  - ansible: 2.10.1
    base: 2.10.2
  - ansible: 2.10.2
    base: 2.10.3
  - ansible: 2.10.3
    base: 2.10.3
  - ansible: 2.10.4
    base: 2.10.3
  - ansible: 2.10.5
    base: 2.10.4
  - ansible: 2.10.6
    base: 2.10.5
  - ansible: 2.10.7
    base: 2.10.5
  - ansible: 3.0.0
    base: 2.10.5
  - ansible: 3.1.0
    base: 2.10.5
  - ansible: 3.2.0
    base: 2.10.7
  - ansible: 3.3.0
    base: 2.10.8
  - ansible: 3.4.0
    base: 2.10.9
  - ansible: 4.0.0
    core: 2.11.0
  - ansible: 4.1.0
    core: 2.11.1
  - ansible: 4.2.0
    core: 2.11.2
  - ansible: 4.3.0
    core: 2.11.3
  - ansible: 4.4.0
    core: 2.11.3
  - ansible: 4.5.0
    core: 2.11.4
  - ansible: 4.6.0
    core: 2.11.5
  - ansible: 4.7.0
    core: 2.11.6
  - ansible: 4.8.0
    core: 2.11.6
  - ansible: 4.9.0
    core: 2.11.6
  - ansible: 4.10.0
    core: 2.11.7
  - ansible: 5.0.0
    core: 2.12.0
  - ansible: 5.0.1
    core: 2.12.0
  - ansible: 5.1.0
    core: 2.12.1
  - ansible: 5.2.0
    core: 2.12.1
  - ansible: 5.3.0
    core: 2.12.2
  - ansible: 5.4.0
    core: 2.12.2
  - ansible: 5.5.0
    core: 2.12.3
  - ansible: 5.6.0
    core: 2.12.4
  - ansible: 5.7.0
    core: 2.12.5
  - ansible: 5.7.1
    core: 2.12.5
  - ansible: 5.8.0
    core: 2.12.5
  - ansible: 5.9.0
    core: 2.12.6
  - ansible: 5.10.0
    core: 2.12.7
  - ansible: 6.0.0
    core: 2.13.0
  - ansible: 6.1.0
    core: 2.13.1
  - ansible: 6.2.0
    core: 2.13.2
  - ansible: 6.3.0
    core: 2.13.3
  - ansible: 6.4.0
    core: 2.13.4
  - ansible: 6.5.0
    core: 2.13.5
  - ansible: 6.6.0
    core: 2.13.6
  - ansible: 6.7.0
    core: 2.13.7
  - ansible: 7.0.0
    core: 2.14.0
  - ansible: 7.1.0
    core: 2.14.1
  - ansible: 7.2.0
    core: 2.14.2
  - ansible: 7.3.0
    core: 2.14.3
  - ansible: 7.4.0
    core: 2.14.4
  - ansible: 7.5.0
    core: 2.14.5
  - ansible: 7.6.0
    core: 2.14.6
  - ansible: 7.7.0
    core: 2.14.7
  - ansible: 8.0.0
    core: 2.15.0
  - ansible: 8.1.0
    core: 2.15.1
  - ansible: 8.2.0
    core: 2.15.2
  - ansible: 8.3.0
    core: 2.15.3
  - ansible: 8.4.0
    core: 2.15.4
  - ansible: 8.5.0
    core: 2.15.5
  - ansible: 8.6.0
    core: 2.15.6
  - ansible: 8.6.1
    core: 2.15.6
  - ansible: 8.7.0
    core: 2.15.7
  - ansible: 9.0.0
    core: 2.16.0
  - ansible: 9.0.1
    core: 2.16.0
  - ansible: 9.1.0
    core: 2.16.1
  - ansible: 9.2.0
    core: 2.16.3
  - ansible: 9.3.0
    core: 2.16.4
  - ansible: 9.4.0
    core: 2.16.5
  - ansible: 9.5.1
    core: 2.16.6
  - ansible: 9.6.0
    core: 2.16.7
  - ansible: 9.6.1
    core: 2.16.7
  - ansible: 9.7.0
    core: 2.16.8
  - ansible: 9.8.0
    core: 2.16.9
  - ansible: 9.9.0
    core: 2.16.10
  - ansible: 9.10.0
    core: 2.16.11
  - ansible: 9.11.0
    core: 2.16.12
  - ansible: 9.12.0
    core: 2.16.13
  - ansible: 9.13.0
    core: 2.16.14
  - ansible: 10.0.0
    core: 2.17.0
  - ansible: 10.0.1
    core: 2.17.0
  - ansible: 10.1.0
    core: 2.17.1
  - ansible: 10.2.0
    core: 2.17.2
  - ansible: 10.3.0
    core: 2.17.3
  - ansible: 10.4.0
    core: 2.17.4
  - ansible: 10.5.0
    core: 2.17.5
  - ansible: 10.6.0
    core: 2.17.6
  - ansible: 10.7.0
    core: 2.17.7
  - ansible: 11.0.0
    core: 2.18.0
  - ansible: 11.1.0
    core: 2.18.1
  - ansible: 11.2.0
    core: 2.18.2
  - ansible: 11.3.0
    core: 2.18.3
  - ansible: 11.4.0
    core: 2.18.4
  - ansible: 11.5.0
    core: 2.18.5
  - ansible: 11.6.0
    core: 2.18.6
  - ansible: 11.7.0
    core: 2.18.6
  - ansible: 11.8.0
    core: 2.18.7
...
