# Copyright 2019-2024 Chris Croome
#
# This file is part of the Webarchitects Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Run as root
  # become: true
  connection: local
  # gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Debug ansible_effective_user_id
      ansible.builtin.debug:
        var: ansible_effective_user_id

    - name: Include ansible role as root for Python >= 3.10.0
      ansible.builtin.include_role:
        name: ansible
      vars:  # noqa var-naming[no-role-prefix]
        ans: true
      when: ansible_facts.python_version is ansible.builtin.version('3.10.0', 'ge', version_type='semver')

    - name: Include ansible role as root for Python <= 3.10.0
      ansible.builtin.include_role:
        name: ansible
      vars:  # noqa var-naming[no-role-prefix]
        ans: true
        ans_pypi_pkgs:
          - name: ansible
            url: https://pypi.org/pypi/ansible
            version: 8.7.0
          - name: ansible-lint
            url: https://pypi.org/pypi/ansible-lint
            venv: ansible
            version: 6.22.2
          - name: dnspython
            type: lib
            url: https://pypi.org/pypi/dnspython
            venv: ansible
            version: latest
          - name: jc
            url: https://pypi.org/pypi/jc
            venv: ansible
            version: latest
          - name: jinja2-ansible-filters
            type: lib
            url: https://pypi.org/pypi/jinja2-ansible-filters
            venv: ansible
            version: latest
          - name: jmespath
            url: https://pypi.org/pypi/jmespath
            venv: ansible
            version: latest
          - name: molecule
            url: https://pypi.org/pypi/molecule
            venv: ansible
            version: latest
          - name: lxml
            type: lib
            url: https://pypi.org/pypi/lxml
            venv: ansible
            version: latest
          - name: molecule-plugins
            extras:
              - docker
            url: https://pypi.org/pypi/molecule-plugins
            venv: ansible
            version: latest
          - name: netaddr
            type: lib
            url: https://pypi.org/pypi/netaddr
            venv: ansible
            version: latest
          - name: pymysql
            type: lib
            url: https://pypi.org/pypi/pymysql
            venv: ansible
            version: latest
          - name: psycopg
            type: lib
            url: https://pypi.org/pypi/psycopg
            venv: ansible
            version: latest
          - name: yamllint
            url: https://pypi.org/pypi/yamllint
            venv: ansible
            version: latest
      when: ansible_facts.python_version is ansible.builtin.version('3.10.0', 'lt', version_type='semver')
...
