# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Find symlinks using ls -l /usr/local/bin
      ansible.builtin.command: ls -l /usr/local/bin
      check_mode: false
      changed_when: false
      register: molecule_root_usr_local_bin_ls

    - name: Set a fact for the results of ls -l /usr/local/bin
      ansible.builtin.set_fact:
        molecule_root_usr_local_bin: "{{ molecule_root_usr_local_bin_ls.stdout | string | community.general.jc('ls') | community.general.json_query('[?link_to].{symlink: filename,dest: link_to}') }}"

    - name: Debug ls symlinks in /usr/local/bin
      ansible.builtin.debug:
        var: molecule_root_usr_local_bin

    - name: Run which ansible
      ansible.builtin.command: which ansible
      check_mode: false
      changed_when: false
      register: molecule_root_which_ansible

    - name: Debug which ansible
      ansible.builtin.debug:
        var: molecule_root_which_ansible.stdout

    - name: Run which ansible -a
      ansible.builtin.command: which ansible -a
      check_mode: false
      changed_when: false
      register: molecule_root_which_ansible_a
      failed_when: molecule_root_which_ansible_a.rc is not regex('^0|1$')

    - name: Check Ansible versions
      ansible.builtin.command: "{{ molecule_ansible_path }} --version"
      check_mode: false
      changed_when: false
      register: molecule_root_ansible_v
      loop: "{{ molecule_root_which_ansible_a.stdout_lines }}"
      loop_control:
        loop_var: molecule_ansible_path

    - name: Set facts for the Ansible versions
      ansible.builtin.set_fact:
        molecule_root_ansible_versions: "{{ molecule_root_ansible_v | community.general.json_query('results[].{path: molecule_ansible_path, version: stdout_lines[0]}') }}"

    - name: Debug ansible versions
      ansible.builtin.debug:
        var: molecule_root_ansible_versions

    - name: List collections
      ansible.builtin.command: ansible-galaxy collection list --format=json
      check_mode: false
      changed_when: false
      register: molecule_collections_list

    - name: Set a fact for the collections that are present
      ansible.builtin.set_fact:
        molecule_collections: "{{ molecule_collections_list.stdout | from_json }}"

    - name: Debug the collections that are present
      ansible.builtin.debug:
        var: molecule_collections
...
